### ISSUE TITLE
Ticking Entity Crash with 2.0.0

### ISSUE THREAD

**Issue by mxnmnm** [MehVahdJukaar/SmarterFarmers#16]
I just downloaded Smarter Farmers 2.0.0 for mc 1.20.1 and I got a ticking farmer entity that was caught by neurina:

Here is the error: https://gist.github.com/mxnmnm/2d864e40aeb65de5a220d1db48356c83

If you need me to produce a full crash log let me know.

**Comment by NolanHewitt** [comment]
Same here. It happened while a farmer was trying to harvest cabbage from farmers delight refabricated. Also happened while harvesting other farmers delight crops. 

Edit: It sometimes happens with vanilla crops as well.

java.lang.ClassCastException: class net.minecraft.class_1739 cannot be cast to class net.minecraft.class_1747 (net.minecraft.class_1739 and net.minecraft.class_1747 are in unnamed module of loader org.quiltmc.loader.impl.launch.knot.KnotClassLoader @271053e1)
	at net.mehvahdjukaar.smarterfarmers.fabric.SFPlatformStuffImpl.getPlant(SFPlatformStuffImpl.java:40)
	at net.mehvahdjukaar.smarterfarmers.SFPlatformStuff.getPlant(SFPlatformStuff.java)
	at net.mehvahdjukaar.smarterfarmers.SFHarvestFarmland.method_19565(SFHarvestFarmland.java:276)
	at net.mehvahdjukaar.smarterfarmers.SFHarvestFarmland.method_18924(SFHarvestFarmland.java:33)
	at net.minecraft.class_4097.method_18923(class_4097.java:66)
	at net.minecraft.class_4103.method_18923(class_4103.java:542)
	at net.minecraft.class_4095.method_19545(class_4095.java:548)
	at net.minecraft.class_4095.method_19542(class_4095.java:493)
	at net.minecraft.class_1646.method_5958(class_1646.java:279)
	at net.minecraft.class_1308.method_6023(class_1308.java:788)
	at net.minecraft.class_1309.method_6007(class_1309.java:2673)
	at net.minecraft.class_1308.method_6007(class_1308.java:550)
	at net.minecraft.class_1296.method_6007(class_1296.java:128)
	at net.minecraft.class_1309.method_5773(class_1309.java:2419)
	at net.minecraft.class_1308.method_5773(class_1308.java:351)
	at net.minecraft.class_1646.method_5773(class_1646.java:320)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.mixinextras$bridge$accept$208(class_1937.java)
	at com.bawnorton.neruina.handler.TickHandler.safelyTickEntities(TickHandler.java:92)
	at net.minecraft.class_1937.wrapOperation$dgo000$neruina$catchTickingEntities$notTheCauseOfTickLag(class_1937.java:17548)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:842)

**Comment by forgettableaccount123** [comment]
[crash-2024-08-17_18.09.40-server.txt](https://github.com/user-attachments/files/16643697/crash-2024-08-17_18.09.40-server.txt)

**Comment by MehVahdJukaar** [comment]
Update moonlight lib. You have an outdated version

**Comment by mxnmnm** [comment]
Isn't the latest version of moonlight this one?: moonlight-1.20-2.12.12-forge

**Comment by chriskeena** [comment]
Time: 2024-08-17 17:10:24
Description: Ticking entity

java.lang.ClassCastException: class net.minecraft.world.item.AirItem cannot be cast to class net.minecraft.world.item.BlockItem (net.minecraft.world.item.AirItem and net.minecraft.world.item.BlockItem are in module minecraft@1.20.1 of loader 'TRANSFORMER' @448cdb47)
	at net.mehvahdjukaar.smarterfarmers.forge.SFPlatformStuffImpl.getPlant(SFPlatformStuffImpl.java:43) ~[smarterfarmers-1.20-2.0.0.jar%23395!/:?] {re:classloading}
	at net.mehvahdjukaar.smarterfarmers.SFPlatformStuff.getPlant(SFPlatformStuff.java) ~[smarterfarmers-1.20-2.0.0.jar%23395!/:?] {re:mixin,re:classloading}
	at net.mehvahdjukaar.smarterfarmers.SFHarvestFarmland.m_6725_(SFHarvestFarmland.java:276) ~[smarterfarmers-1.20-2.0.0.jar%23395!/:?] {re:mixin,re:classloading}
	at net.mehvahdjukaar.smarterfarmers.SFHarvestFarmland.m_6725_(SFHarvestFarmland.java:33) ~[smarterfarmers-1.20-2.0.0.jar%23395!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.entity.ai.behavior.Behavior.m_22558_(Behavior.java:66) ~[client-1.20.1-20230612.114412-srg.jar%23426!/:?] {re:classloading,re:mixin}
	at net.minecraft.world.entity.ai.behavior.GateBehavior.m_257174_(GateBehavior.java:72) ~[client-1.20.1-20230612.114412-srg.jar%23426!/:?] {re:classloading,re:mixin}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at net.minecraft.world.entity.ai.behavior.GateBehavior.m_22558_(GateBehavior.java:72) ~[client-1.20.1-20230612.114412-srg.jar%23426!/:?] {re:classloading,re:mixin}
	at net.minecraft.world.entity.ai.Brain.m_21963_(Brain.java:548) ~[client-1.20.1-20230612.114412-srg.jar%23426!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.world.entity.ai.Brain.m_21865_(Brain.java:493) ~[client-1.20.1-20230612.114412-srg.jar%23426!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.world.entity.npc.Villager.m_8024_(Villager.java:209) ~[client-1.20.1-20230612.114412-srg.jar%23426!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forge:forge_method_redirector,re:classloading,pl:accesstransformer:B,xf:fml:forge:forge_method_redirector,pl:mixin:APP:moonlight-common.mixins.json:VillagerMixin,pl:mixin:APP:kiwi.mixins.json:VillagerAccess,pl:mixin:APP:tombstone.mixins.json:accessor.VillagerAccessor,pl:mixin:APP:smarterfarmers-common.mixins.json:VillagerAccessor,pl:mixin:APP:smarterfarmers-common.mixins.json:VillagerMixin,pl:mixin:APP:smarterfarmers.mixins.json:VillagerMixin,pl:mixin:A}
	at net.minecraft.world.entity.Mob.m_6140_(Mob.java:768) ~[client-1.20.1-20230612.114412-srg.jar%23426!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:moonlight-common.mixins.json:EntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:accessors.entity.AccessorMob,pl:mixin:APP:tombstone.mixins.json:MobMixin,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2546) ~[client-1.20.1-20230612.114412-srg.jar%23426!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:better_climbing.xplat_mixins.json:LivingEntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:accessors.entity.AccessorLivingEntity,pl:mixin:APP:bookshelf.common.mixins.json:patches.entity.MixinLivingEntity,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:dynamiclightsreforged.mixins.json:lightsource.LivingEntityMixin,pl:mixin:APP:tombstone.mixins.json:LivingEntityMixin,pl:mixin:APP:betterarcheology.mixins.json:TorrentTotemItemTickMixin,pl:mixin:APP:betterdeserttemples.mixins.json:PharaohKilledMixin,pl:mixin:APP:snowyspirit-common.mixins.json:EntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.Mob.m_8107_(Mob.java:536) ~[client-1.20.1-20230612.114412-srg.jar%23426!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:moonlight-common.mixins.json:EntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:accessors.entity.AccessorMob,pl:mixin:APP:tombstone.mixins.json:MobMixin,pl:mixin:A}
	at net.minecraft.world.entity.AgeableMob.m_8107_(AgeableMob.java:128) ~[client-1.20.1-20230612.114412-srg.jar%23426!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2296) ~[client-1.20.1-20230612.114412-srg.jar%23426!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:better_climbing.xplat_mixins.json:LivingEntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:accessors.entity.AccessorLivingEntity,pl:mixin:APP:bookshelf.common.mixins.json:patches.entity.MixinLivingEntity,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:dynamiclightsreforged.mixins.json:lightsource.LivingEntityMixin,pl:mixin:APP:tombstone.mixins.json:LivingEntityMixin,pl:mixin:APP:betterarcheology.mixins.json:TorrentTotemItemTickMixin,pl:mixin:APP:betterdeserttemples.mixins.json:PharaohKilledMixin,pl:mixin:APP:snowyspirit-common.mixins.json:EntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:337) ~[client-1.20.1-20230612.114412-srg.jar%23426!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:moonlight-common.mixins.json:EntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:accessors.entity.AccessorMob,pl:mixin:APP:tombstone.mixins.json:MobMixin,pl:mixin:A}
	at net.minecraft.world.entity.npc.Villager.m_8119_(Villager.java:248) ~[client-1.20.1-20230612.114412-srg.jar%23426!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forge:forge_method_redirector,re:classloading,pl:accesstransformer:B,xf:fml:forge:forge_method_redirector,pl:mixin:APP:moonlight-common.mixins.json:VillagerMixin,pl:mixin:APP:kiwi.mixins.json:VillagerAccess,pl:mixin:APP:tombstone.mixins.json:accessor.VillagerAccessor,pl:mixin:APP:smarterfarmers-common.mixins.json:VillagerAccessor,pl:mixin:APP:smarterfarmers-common.mixins.json:VillagerMixin,pl:mixin:APP:smarterfarmers.mixins.json:VillagerMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693) ~[client-1.20.1-20230612.114412-srg.jar%23426!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinServerLevel,pl:mixin:APP:mixins.hammerlib.json:ServerLevelMixin,pl:mixin:APP:snowrealmagic.mixins.json:ServerLevelMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:flood.mixins.json:ServerLevelMixin,pl:mixin:A}
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[client-1.20.1-20230612.114412-srg.jar%23426!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sereneseasons.mixins.json:MixinLevel,pl:mixin:APP:dynamiclightsreforged.mixins.json:WorldMixin,pl:mixin:APP:mixins.hammerlib.json:LevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[client-1.20.1-20230612.114412-srg.jar%23426!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinServerLevel,pl:mixin:APP:mixins.hammerlib.json:ServerLevelMixin,pl:mixin:APP:snowrealmagic.mixins.json:ServerLevelMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:flood.mixins.json:ServerLevelMixin,pl:mixin:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23426!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[client-1.20.1-20230612.114412-srg.jar%23426!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:sereneseasons.mixins.json:MixinServerLevel,pl:mixin:APP:mixins.hammerlib.json:ServerLevelMixin,pl:mixin:APP:snowrealmagic.mixins.json:ServerLevelMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:flood.mixins.json:ServerLevelMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%23426!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23426!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23426!/:?] {re:mixin,pl:runtimedistcleaner:A,re:computing_frames,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:bobby.mixins.json:IntegratedServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23426!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23426!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:842) ~[?:?] {re:mixin}

**Comment by MehVahdJukaar** [comment]
ok many people writing here. one of you idnt have tha updated. other must be some weird issue with some crop

**Comment by mxnmnm** [comment]
Ok here is the full crash report:

https://gist.github.com/mxnmnm/927850c28c7b474f68f643ff126a053a

**Comment by NolanHewitt** [comment]
> ok many people writing here. one of you idnt have tha updated. other must be some weird issue with some crop

I'm trying 2.0.1 that was just uploaded and so far it seems to have fixed it for me.

**Comment by mxnmnm** [comment]
seems to be fixed
